import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :helloworld, HelloworldWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Helloworld.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Database configuration
config :helloworld, Helloworld.Repo,
  url: System.get_env("postgresql://postgres:jrpZXGGIiCoodKcpZQBVAiRVxlWyMGKr@shortline.proxy.rlwy.net:22917/railway
"),
  pool_size: 20,              # Increase pool size to handle more requests
  queue_target: 5000,         # Increase queue time to 5 seconds
  queue_interval: 1000,       # Check for available connections every second
  ssl: true                   # Use SSL for the connection

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
